export interface Publication {
  title: string;
  url: string;
  authors: string;
  venue: string;
  tag: string;
  year: number;
  award?: string;
}

export const publications: Publication[] = [
  {
    title: 'Efficient Low-Rank Index Routing for High-Dimensional Approximate Nearest Neighbor Search',
    url: 'https://www.sciencedirect.com/science/article/abs/pii/S0306457325004005',
    authors: 'Y. Li, S. Wang, Z. Chen, Z. Peng',
    venue: 'Information Processing & Management',
    tag: 'IPM',
    year: 2026,
  },
  {
    title: 'Dependency Relationships-Enhanced Attentive Group Recommendation in HINs',
    url: 'https://link.springer.com/article/10.1007/s11280-025-01374-8',
    authors: 'J. Zhang, Z. Chen, S. Wang, X. Yang, D. Han, Z. Peng',
    venue: 'World Wide Web Journal',
    tag: 'WWWJ',
    year: 2025,
  },
  {
    title: 'LLM-based Dialogue Labeling for Multiturn Adaptive RAG',
    url: 'https://aclanthology.org/2025.emnlp-industry.72.pdf',
    authors: 'Z. Chen, B. Xie, S. Srinivasan, M. Ramanathan, R. Maragoud, Q. Liu',
    venue: 'EMNLP (Industry)',
    tag: 'EMNLP',
    year: 2025,
  },
  {
    title: 'REIC: RAG-Enhanced Intent Classification at Scale',
    url: 'https://arxiv.org/pdf/2506.00210',
    authors: 'Z. Zhang, M. Yang, Z. Chen, Y. Zhuang, S.-T. Pi, Q. Liu, R. Maragoud, V. Nguyen, A. Beniwal',
    venue: 'EMNLP (Industry)',
    tag: 'EMNLP',
    year: 2025,
  },
  {
    title: 'Wizard of Shopping: Target-Oriented E-commerce Dialogue Generation with Decision Tree Branching',
    url: 'https://aclanthology.org/2025.acl-long.641/',
    authors: 'X. Li, Z. Chen, J. Choi, N. Vedula, B. Fetahu, O. Rokhlenko, S. Malmasi',
    venue: 'ACL',
    tag: 'ACL',
    year: 2025,
  },
  {
    title: 'Approximate Vector Set Search: A Bio-Inspired Approach for High-Dimensional Spaces',
    url: 'https://ieeexplore.ieee.org/document/11113061/',
    authors: 'W. Yang, S. Wang, Z. Chen, Y. Sun, Z. Peng',
    venue: 'ICDE',
    tag: 'ICDE',
    year: 2025,
  },
  {
    title: 'Joinable Search Over Multi-Source Spatial Datasets: Overlap, Coverage, and Efficiency',
    url: 'https://www.computer.org/csdl/proceedings-article/icde/2025/360300a585/26FZzmi551S',
    authors: 'Y. Li, S. Wang, Z. Chen, S. Chen, Z. Peng',
    venue: 'ICDE',
    tag: 'ICDE',
    year: 2025,
  },
  {
    title: 'Identifying High Consideration E-Commerce Search Queries',
    url: 'https://aclanthology.org/2024.emnlp-industry.42/',
    authors: 'Z. Chen, B. Fetahu, J. Choi, S. Malmasi',
    venue: 'EMNLP (Industry)',
    tag: 'EMNLP',
    year: 2024,
  },
  {
    title: 'Unbiased Learning-to-Rank Needs Unconfounded Propensity Estimation',
    url: 'https://doi.org/10.1145/3626772.3657772',
    authors: 'D. Luo, L. Zou, Q. Ai, Z. Chen, C. Li, D. Yin, B.D. Davison',
    venue: 'SIGIR',
    tag: 'SIGIR',
    year: 2024,
  },
  {
    title: 'Enhancing Low-Resource LLMs Classification with PEFT and Synthetic Data',
    url: 'https://aclanthology.org/2024.lrec-main.533/',
    authors: 'P. Patwa, S. Filice, Z. Chen, G. Castellucci, O. Rokhlenko, S. Malmasi',
    venue: 'LREC-COLING',
    tag: 'LREC-COLING',
    year: 2024,
  },
  {
    title: 'Training-free Optimization of Generative Recommender Systems using Large Language Model Optimizers',
    url: 'https://aclanthology.org/2024.acl-long.295/',
    authors: 'LK. Şenel, B. Fetahu, D. Yoshida, Z. Chen, G. Castellucci, N. Vedula, J. Choi, S. Malmasi',
    venue: 'ACL',
    tag: 'ACL',
    year: 2024,
  },
  {
    title: 'InstructPTS: Instruction-Tuning LLMs for Product Title Summarization',
    url: 'https://aclanthology.org/2023.emnlp-industry.63/',
    authors: 'B. Fetahu, Z. Chen, O. Rokhlenko, S. Malmasi',
    venue: 'EMNLP (Industry)',
    tag: 'EMNLP',
    year: 2023,
  },
  {
    title: 'Multi-Coner V2: A Large Multilingual Dataset for Fine-grained and Noisy Named Entity Recognition',
    url: 'https://aclanthology.org/2023.findings-emnlp.134/',
    authors: 'B. Fetahu, Z. Chen, S. Kar, O. Rokhlenko, S. Malmasi',
    venue: 'EMNLP (Findings)',
    tag: 'EMNLP',
    year: 2023,
  },
  {
    title: 'Generate-then-Retrieve: Intent-Aware FAQ Retrieval in Product Search',
    url: 'https://aclanthology.org/2023.acl-industry.73/',
    authors: 'Z. Chen, J. Choi, B. Fetahu, O. Rokhlenko, S. Malmasi',
    venue: 'ACL (Industry)',
    tag: 'ACL',
    year: 2023,
  },
  {
    title: 'Answering Unanswered Questions through Semantic Reformulations in Spoken QA',
    url: 'https://aclanthology.org/2023.acl-industry.70/',
    authors: 'P. Faustini, Z. Chen, B. Fetahu, O. Rokhlenko, S. Malmasi',
    venue: 'ACL (Industry)',
    tag: 'ACL',
    year: 2023,
  },
  {
    title: 'Model-based Unbiased Learning to Rank',
    url: 'https://dl.acm.org/doi/10.1145/3539597.3570395',
    authors: 'D. Luo, L. Zou, Q. Ai, Z. Chen, D. Yin, B.D. Davison',
    venue: 'WSDM',
    tag: 'WSDM',
    year: 2023,
  },
  {
    title: 'Reinforced Question Rewriting for Conversational Question Answering',
    url: 'https://aclanthology.org/2022.emnlp-industry.36/',
    authors: 'Z. Chen, J. Zhao, A. Fang, B. Fetahu, O. Rokhlenko, S. Malmasi',
    venue: 'EMNLP (Industry)',
    tag: 'EMNLP',
    year: 2022,
  },
  {
    title: 'StruBERT: Structure-aware BERT for Table Search and Matching',
    url: 'https://doi.org/10.1145/3485447.3511972',
    authors: 'M. Trabelsi, Z. Chen, S. Zhang, J. Heflin, B. D. Davison',
    venue: 'WWW',
    tag: 'WWW',
    year: 2022,
  },
  {
    title: 'MGNETS: Multi-Graph Neural Networks for Table Search',
    url: 'https://dl.acm.org/doi/abs/10.1145/3459637.3482140',
    authors: 'Z. Chen, M. Trabelsi, J. Heflin, D. Yin, B. D. Davison',
    venue: 'CIKM',
    tag: 'CIKM',
    year: 2021,
  },
  {
    title: 'Neural Ranking Models for Document Retrieval',
    url: 'https://doi.org/10.1007/s10791-021-09398-0',
    authors: 'M. Trabelsi, Z. Chen, J. Heflin, B.D. Davison',
    venue: 'Information Retrieval Journal',
    tag: 'IRJ',
    year: 2021,
  },
  {
    title: 'WTR: A Test Collection for Web Table Retrieval',
    url: 'https://dl.acm.org/doi/10.1145/3404835.3463260',
    authors: 'Z. Chen, S. Zhang, B. D. Davison',
    venue: 'SIGIR',
    tag: 'SIGIR',
    year: 2021,
  },
  {
    title: 'A Hybrid Deep Model for Learning to Rank Data Tables',
    url: 'https://ieeexplore.ieee.org/document/9378185',
    authors: 'M. Trabelsi, Z. Chen, J. Heflin, B.D. Davison',
    venue: 'IEEE BigData',
    tag: 'BigData',
    year: 2020,
  },
  {
    title: 'Relational Graph Embeddings for Table Retrieval',
    url: 'https://ieeexplore.ieee.org/document/9378239',
    authors: 'M. Trabelsi*, Z. Chen*, B. D. Davison, J. Heflin',
    venue: 'BigGraphs (at IEEE BigData)',
    tag: 'BigGraphs',
    year: 2020,
  },
  {
    title: 'Towards Knowledge Acquisition of Metadata on AI Progress',
    url: 'https://ceur-ws.org/Vol-2721/paper559.pdf',
    authors: 'Z. Chen*, M. Trabelsi*, B. D. Davison, J. Heflin',
    venue: 'ISWC (Demo)',
    tag: 'ISWC',
    year: 2020,
  },
  {
    title: 'Table Search Using a Deep Contextualized Language Model',
    url: 'https://dl.acm.org/doi/10.1145/3397271.3401044',
    authors: 'Z. Chen, M. Trabelsi, J. Heflin, Y. Xu, B. D. Davison',
    venue: 'SIGIR',
    tag: 'SIGIR',
    year: 2020,
  },
  {
    title: 'Pretrained Generalized Autoregressive Model with Adaptive Probabilistic Label Clusters for Extreme Multi-label Text Classification',
    url: 'https://proceedings.mlr.press/v119/ye20a.html',
    authors: 'H. Ye, Z. Chen, D.-H. Wang, B. D. Davison',
    venue: 'ICML',
    tag: 'ICML',
    year: 2020,
  },
  {
    title: 'Leveraging Schema Labels to Enhance Dataset Search',
    url: 'https://dl.acm.org/doi/10.1007/978-3-030-45439-5_18',
    authors: 'Z. Chen, H. Jia, J. Heflin, B. D. Davison',
    venue: 'ECIR',
    tag: 'ECIR',
    year: 2020,
  },
  {
    title: 'Generating Schema Labels through Dataset Content Analysis',
    url: 'https://dl.acm.org/doi/10.1145/3184558.3191601',
    authors: 'Z. Chen, H. Jia, J. Heflin, B. D. Davison',
    venue: 'WWW (Profiles & Data:Search Workshop)',
    tag: 'WWW',
    year: 2018,
    award: 'Best Paper Award',
  },
];
